apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: diary-gateway
  namespace: diary
  labels:
    release: istio
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*.diary.localhost"
