creation_rules:
- path_regex: .*\.yaml$
  encrypted_regex: '^(data|stringData|parameters)$'
  gcp_kms: >-
    projects/programming-diary-prod/locations/global/keyRings/sops/cryptoKeys/sops-key

- path_refex: .*\.env$
  gcp_kms: >-
    projects/programming-diary-prod/locations/global/keyRings/sops/cryptoKeys/sops-key