creation_rules:
- path_regex: .*\.yaml$
  encrypted_regex: '^(data|stringData)$'
  pgp: >-
    A893A7CE422E149B3CCC8A49A1924D586049F75E

- path_refex: .*\.env$
  pgp: >-
    A893A7CE422E149B3CCC8A49A1924D586049F75E