apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: users
    version: v1
  name: users
  namespace: diary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
        version: v1
    spec:
      containers:
      - image: rasouza/diary-users:latest
        name: users
        ports:
        - containerPort: 8000
      restartPolicy: Always