apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: diary
  name:  idp-deployment
  labels:
    app:  idp
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:  idp
        version: v1
    spec:
      containers:    
      - image:  oryd/hydra:v1.4.5
        name:  idp
        command:
        - hydra
        - serve
        - all
        - --dangerous-force-http
        livenessProbe:
          httpGet:
            path: /health/ready
            port: 4444
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 4444
        env:
        - name: DSN
          value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_DATABASE)?search_path=$(DB_SCHEMA)"
        envFrom:
        - configMapRef:
            name: idp-config
        - secretRef:
            name: idp-secret
        ports:
        - containerPort:  4444
          name:  public
        - containerPort: 4445
          name: admin
  revisionHistoryLimit: 0
