apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: argocd

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- ingress.yaml
- namespace.yaml
# - cloudflare.yaml

patchesStrategicMerge:
- sso.yaml
- sops/enablePlugins.yaml
- sops/sopsSecretsGenerator.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-server
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: --insecure
  
# - target:
#     version: v1
#     kind: Secret
#     name: argocd-secret
#   path: github-secret.yaml
    