apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  admin.enabled: "false" 
  url: https://argocd.rasouza.dev

  dex.config: |
    connectors:
      # Programming Diary Organization
      - type: github
        id: github
        name: GitHub
        config:
          clientID: b61a4e47f85582578249
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: programming-diary