---
# Source: am/templates/api/api-autoscaler.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: idp-am-management-api
  labels:
    app.kubernetes.io/name: am
    app.kubernetes.io/instance: idp
    app.kubernetes.io/version: 3.5.0
    app.kubernetes.io/component: "management-api"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: am-1.0.12
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: idp-am-management-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
