apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: buildkite
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/rasouza/diary-infra.git
    targetRevision: master
    path: buildkite

    helm:
      

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: buildkite

  # Sync policy
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
