---
- name: ArgoCD set up
  hosts: localhost
  tasks:
    - name: Ensures argocd Namespace exists
      k8s:
        state: present
        api_version: v1
        kind: Namespace
        name: argocd
    - name: Ensures SSO ConfigMap is installed
      k8s:
        state: present
        namespace: argocd
        src: ../argocd/sso.yaml
    - name: Ensures ArgoCD is installed
      k8s:
        state: present
        namespace: argocd
        src: ../argocd/argocd.yaml
    - name: Ensures ArgoCD is exposed
      k8s:
        state: present
        namespace: argocd
        src: ../argocd/gateway.yaml