---
- name: ArgoCD set up
  hosts: localhost
  tasks:
    - name: Ensures argocd Namespace exists
      k8s:
        state: present
        api_version: v1
        kind: Namespace
        name: argocd
    - name: Ensures ArgoCD is installed
      k8s:
        state: present
        namespace: argocd
        src: ../argocd/argocd.yaml
    - name: Ensures ArgoCD is exposed
      k8s:
        state: present
        namespace: argocd
        src: ../argocd/gateway.yaml
    - name: Ensures ArgoCD is in /etc/hosts
      become: true
      lineinfile:
        dest: /etc/hosts
        regexp: '.*argocd$'
        line: '127.0.0.1 argocd.localhost'
        state: present