---
- name: "Installs Istio Service Mesh"
  hosts: localhost
  tasks:
    - name: Check if istioctl is installed
      shell: which istioctl
    - name: Installs Istio Service Mesh
      shell: istioctl manifest apply -f ../istio/istio-operator.yaml
    - name: Ensures Kiali, Jaeger, Prometheus and Grafana is exposed
      shell: kubectl apply -f ../istio/virtualsvc.yaml