apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: idp

namespace: idp

resources:
- am/templates/api/api-autoscaler.yaml
- am/templates/api/api-configmap.yaml
- am/templates/api/api-deployment.yaml
- am/templates/api/api-ingress.yaml
- am/templates/api/api-service.yaml
- am/templates/gateway/gateway-autoscaler.yaml
- am/templates/gateway/gateway-configmap.yaml
- am/templates/gateway/gateway-deployment.yaml
- am/templates/gateway/gateway-ingress.yaml
- am/templates/gateway/gateway-service.yaml
- am/templates/ui/ui-autoscaler.yaml
- am/templates/ui/ui-configmap.yaml
- am/templates/ui/ui-deployment.yaml
- am/templates/ui/ui-service.yaml
- am/templates/ui/ui-ingress.yaml