apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: idp

namespace: idp

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
  - name: idp-env
    envs: 
    - envs/kratos.env
  - name: idp-config
    files:
    - data/identity.schema.json
    - data/oidc.github.jsonnet

# secretGenerator:
#   - name: idp-secret
#     type: Opaque
#     envs:
#       - envs/db.env
#       - envs/secrets.env

generators:
- secret-generator.yaml